// SURAMERICANA 
function cambiartext(){let text = document.getElementById('suramericana').innerHTML = 'Atlético Nacional se consagró campeón de la Recopa Sudamericana tras vencer 4-1 (5-3 en el global) a Chapecoense en el partido de vuelta en el Atanasio Girardot.'}

// LIBERTADORES 
function cambiartext1(){let text = document.getElementById('libertadores-1989').innerHTML = 'Más de 30 mil hinchas verdes para presenciar la final ante Olimpia. El trasteo más grande de la historia del fútbol colombiano y quizás mundial, lo protagonizó la hinchada más popular de Colombia que se movilizó vía terrestre y aérea. ___________________________________'}

function cambiartext2(){let text = document.getElementById('libertadores-2016').innerHTML = 'Atlético Nacional ganó 10 partidos en esta edición de Libertadores (3E 1D); logró un 71% de victorias en el torneo, el mayor porcentaje entre todos los campeones de la competencia en este siglo (junto a Gremio de Brasil en 2017 y Boca Juniors de Argentina en 2003).'}

// MERCONORTE
function cambiartext3(){let text = document.getElementById('merconorte-1998').innerHTML = 'Se jugó por primera vez en 1998, y fue el reemplazo de la Copa Conmebol, aunque partida en dos: Merconorte y Mercosur. ______________________________________________________________________'}
function cambiartext4(){let text = document.getElementById('merconorte-2000').innerHTML = 'La Copa Merconorte de 2000 tuvo por tercera vez consecutiva un campeón de un mismo país de origen: Colombia. Atlético Nacional a su vez, obtuvo su segundo título revalidando el conseguido en la primera edición en el año 1998.'}

// INTERAMERICANA
function cambiartext5(){let text = document.getElementById('interamerican-1990').innerHTML = 'La Copa Interamericana se realizaba un año después entre el ganador de la Copa Libertadores de América y el ganador de la Copa de Campeones de la CONCACAF.'}
function cambiartext6(){let text = document.getElementById('interamerican-1997').innerHTML = 'La participación del club colombiano en este certamen fue debido a la renuncia de Gremio de Brasil, quien había ganado la Copa Libertadores 1995 frente a los verdes.'}

// SUPERLIGA
function cambiartext7(){let text = document.getElementById('superliga-2012').innerHTML = 'Jefferson Duque, recién llegado de Deportivo Rionegro y John Freddy Pajoy, fueron las figuras incuestionables del nuevo título que ya reposa en las vitrinas nacionalistas de un equipo que tuvo además en Avilés Hurtado, Macnelly Torres, Cristian Bonilla y Alexander Mejía a figuras incuestionables de la nueva leyenda nacionalista.'}
function cambiartext8(){let text = document.getElementById('superliga-2016').innerHTML = 'fue la quinta edición del torneo oficial de fútbol colombiano que enfrenta a los campeones del FPC 2015, Deportivo Cali, campeón del Apertura 2015, contra Atlético Nacional, campeón del Finalización 2015. Otra fecha gloriosa para el gran verde paisa con canticos narrados por Munera (El Paisita).___________'}

// COPA COLOMBIA
function cambiartext9(){let text = document.getElementById('copacolombia-2012').innerHTML = 'Con ese triunfo, Atlético Nacional represento a Colombia en la Copa Sudamericana del 2013. Este era su primera copa de colombia y el 24 de noviembre del 2021 ya alzanza la nuemro cinco que guarda en su vitrina ____________________________________________________________________________________'}
function cambiartext10(){let text = document.getElementById('copacolombia-2013').innerHTML = 'El año 2013 es quizá uno de los años que los hinchas verdolagas recuerdan con mayor cariño. Aquel año el equipo dirigido por Juan Carlos Osorio lograría una hazaña que al día de hoy no ha podido ser replicada: coronarse campeón en los tres torneos del año. _________________________________________'}
function cambiartext11(){let text = document.getElementById('copacolombia-2016').innerHTML = 'En la primera parte, Junior intentó ser el de la propuesta, pero perdía muy rápido el esférico y en cada contraataque de Nacional, aparecía la figura de Miguel Borja: el atlanticense provocó las dos primeras llegadas de gol, pero Viera, en la primera, y su puntería, en la segunda, le impidieron anotar.________-'}
function cambiartext12(){let text = document.getElementById('copacolombia-2018').innerHTML = 'La escuadra verde tomó con seriedad esta oportunidad ante la respuesta de su afición y por el deseo de volver a la Libertadores.Con Vladimir Hernández y Steven Lucumí registró sus primeras opciones frente a un cuadro albo que fue inferior al reto. __________________________________________________________________________________________-'}
function cambiartext13(){let text = document.getElementById('copacolombia-2021').innerHTML = 'Por momentos, el conjunto dirigido por Alexis Márquez tomó una postura cuidadosa, con el fin de evitar que se ampliara el marcador global. Pero los hombres de Alejandro Restrepo tampoco hicieron mucho para que así fuera.'}

// LIGA COLOMBIANA
function cambiartext14(){let text = document.getElementById('liga-1954').innerHTML = 'Atlético Nacional se coronó campeón por primera vez en su historia frente al América de Cali en Palmira con un resultado de 6-2 '}
function cambiartext15(){let text = document.getElementById('liga-1973').innerHTML = 'El campeón de esta edición fue el Atlético Nacional, logrando su segunda estrella. El subcampeón fue Millonarios.'}
function cambiartext16(){let text = document.getElementById('liga-1976').innerHTML = 'Este campeonato constó de una serie todos contra todos, además de un Hexagonal final para definir el campeón de la temporada.'}
function cambiartext17(){let text = document.getElementById('liga-1981').innerHTML = 'El campeón de esta edición fue el Atlético Nacional, que consiguió su cuarto título, y el subcampeón fue Deportes Tolima. '}
function cambiartext18(){let text = document.getElementById('liga-1991').innerHTML = 'El Torneo Apertura se disputó mediante 12 fechas, bajo el sistema de triangulares y pentagonales regionales, y el Finalización con 28 jornadas más,______________________________'}
function cambiartext19(){let text = document.getElementById('liga-1994').innerHTML = 'Este torneo fue el último que se disputó con campeón en el mes de diciembre, ya que a partir del siguiente campeonato, el calendario del fútbol colombiano sería acorde con el europeo.'}
function cambiartext20(){let text = document.getElementById('liga-1999').innerHTML = 'En los torneos Apertura y Finalización se dividieron los 16 equipos en dos octogonales, disputándose siete fechas. ________________________________________________________________'}
function cambiartext21(){let text = document.getElementById('liga-2005').innerHTML = 'Atlético Nacional se consagra campeón del Torneo Apertura-2005 de Colombia al vencer por 2-0 al Independiente Santa Fe. __________________________________________________________'}
function cambiartext22(){let text = document.getElementById('liga-2007-1').innerHTML = 'La temporada 2007 de Atlético Nacional fue la temporada número 60 en la Primera A. Los aspectos más destacados de la temporada incluyen el bicampeonato y la clasificación a la libertadores del próximo año.'}
function cambiartext23(){let text = document.getElementById('liga-2007-2').innerHTML = ' En la primera etapa se juegan 18 fechas bajo el sistema de todos contra todos, al término de los cuales los ocho primeros clasificados avanzan a los cuadrangulares semifinales.'}
function cambiartext24(){let text = document.getElementById('liga-2011').innerHTML = 'El club ganó el Torneo Apertura, logrando así su 11º título en la Primera División del Fútbol Profesional Colombiano.________________________________________________________________________'}
function cambiartext25(){let text = document.getElementById('liga-2013-1').innerHTML = 'La gran novedad es que el uniforme a partir de este año fue hecho por la marca estadounidense Nike.​ La primera equipación fue camisa con rayas verdes delgadas, pantalón blanco y calcetines verdes con detalles blancos.'}
function cambiartext26(){let text = document.getElementById('liga-2013-2').innerHTML = 'Con este torneo, el club Atlético Nacional conseguiría ser el ganador de los dos torneos de la temporada 2013 y la Copa Colombia 2013, faltando solamente la Superliga de Colombia ganada por Santa Fe.'}
function cambiartext27(){let text = document.getElementById('liga-2014').innerHTML = 'Logro una temporada de ensueño en el 2013 (ganó 3 de los 4 torneos disputados en el año, incluyendo un bicampeonato de liga y el segundo título en toda su historia de la copa doméstica)'}
function cambiartext28(){let text = document.getElementById('liga-2015').innerHTML = 'El club inició la temporada con el subtítulo de la Superliga contra Santa Fe, en el Torneo Apertura aunque el equipo hizo una actuación irregular logró clasificar a cuartos de final, pero fue eliminado por el Deportivo Cali.'}
function cambiartext29(){let text = document.getElementById('liga-2017').innerHTML = 'En el 2017 fue el utimo titulo que atletico nacional ah levantando hast el momento por la liga colombiana,, ajustando un total de 4 años hasta el momento si poder levantr este titulo, se espera que para este año si se logre.'}